### ISSUE TITLE
Add License to Repository

### ISSUE THREAD

**Issue by Huntera** [prateek/nifi-parcel#10]
Hello, 

Can you [add some kind of open source license](https://help.github.com/articles/adding-a-license-to-a-repository/) to allow for contribution, distribution, and use by other people? Including something like the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license would be great for people looking to create a NiFi Cloudera parcel.

Thank you.

**Comment by prateek** [comment]
Sure. I’ll put one up later today.

**Comment by prateek** [comment]
@Huntera added the license. Contributions/forks welcome!
