### ISSUE TITLE
How we can add new bundle nar to existing nifi service running in cdh ?

### ISSUE THREAD

**Issue by pmuthal** [prateek/nifi-parcel#3]
Hi  , 

Would like to know about how i can add a new developed nar of processor in existing CDH service of nifi ?

**Comment by prateek** [comment]
@pmuthal the quick version would be to bundle the NAR in this parcel (you'll have to find the appropriate folder) at build time. This might not be ideal because you'll have to rebuild/deploy the parcel whenever your NAR changes, but it will get you started quickly.
